#!/bin/bash

if [ $# -le 0 ]; then
    echo "Usage \"bash taggen.sh [--tag|--untag]\""
    echo "--tag: Generate tags for the project \(using ctags\)"
    echo "--untag: Remove the \"tags\" file generated by ctags"
    exit 1
fi 

if [ $# -gt 1 ]; then
    echo "Extra arguments will be ignored"
fi 

if [ $1 == "--tag" ]; then
    echo "Generating project tags"
    ctags -R --languages=C,C++
elif [ $1 == "--untag" ]; then
    echo "Removing tags"
    rm -f tags
else
    echo "Unknow option: $1" 
    echo "Usage \"bash taggen.sh [--tag|--untag]\""
    echo "--tag: Generate tags for the project \(using ctags\)"
    echo "--untag: Remove the \"tags\" file generated by ctags"
    exit 1
fi
